"""
Centralized pool registry for Uniswap V3 USDC/USDT pool data collection.

Single source of truth for all pool definitions — replaces duplicated dicts
across getTicks.py, getPoolData_daily.py, getPoolData_hourly_messari.py, and MCI_ticks.py.

Pool definitions are loaded from data/discovery/selected_pools.json, which is
generated by findTopPools.py.  The JSON format mirrors the POOLS dict:
    { "pool_address": {"pair": "TOKEN0/TOKEN1", "fee_tier": 500, "stablecoin": "USDC", "active": true}, ... }
"""

import json
import os
import pandas as pd

STABLECOINS = ["USDC", "USDT"]

# Token addresses on Ethereum mainnet
TOKEN_ADDRESSES = {
    "USDC": "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48",
    "USDT": "0xdac17f958d2ee523a2206206994597c13d831ec7",
    "WETH": "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2",
    "WBTC": "0x2260fac5e5542a773aa44fbcfedf7c193bc2c599",
    "DAI": "0x6b175474e89094c44da98b954eedeac495271d0f",
}

# ---------------------------------------------------------------------------
# USDC-backed tokens excluded from USDT pairs
# ---------------------------------------------------------------------------
# When analysing USDT liquidity we exclude pools where the counterpart token
# derives its value primarily from USDC reserves.  Including them would
# conflate USDC stability risk with USDT's, defeating the purpose of
# studying each stablecoin independently.
#
# Each entry maps a token symbol to a short explanation of WHY it is
# considered USDC-backed.  Sources are listed at the end of this block.
#
# Tokens evaluated and NOT excluded (no significant USDC backing):
#   LUSD  — backed solely by ETH (Liquity V1) / ETH LSTs (V2)
#   GUSD  — fiat USD in bank accounts and T-bills (Gemini Trust)
#   TUSD  — fiat USD in escrow at regulated banks (TrueUSD)
#   USDD  — backed by TRX and USDT (TRON DAO Reserve)
#   USDP  — fiat USD in FDIC-insured banks and T-bills (Paxos)
#   USDM  — backed by short-term US Treasuries (Mountain Protocol)
#   FEI   — backed by ETH as Protocol-Controlled Value; USDC was explicitly
#           excluded by design (Fei Protocol, defunct Aug 2022)
#
# Sources:
#   DAI   — https://www.theblock.co/post/236139/makerdao-dai-collateral-usdc
#   FRAX  — https://www.gemini.com/cryptopedia/frax-crypto-protocol
#   USDe  — https://docs.ethena.fi/how-usde-works
#   OUSD  — https://docs.originprotocol.com/yield-bearing-tokens/origin-dollar-ousd
#   MIM   — https://www.gemini.com/cryptopedia/magic-internet-money-mim-crypto
#   BOB   — https://docs.zkbob.com/zkbob-overview/bob-stablecoin
#   alUSD — https://alchemixfi.medium.com/new-collateral-types-c9e32203eae4
#   cUSDC — https://docs.compound.finance/v2/ctokens/
#   aUSDC — https://docs.aave.com/developers/tokens/atoken
# ---------------------------------------------------------------------------
USDC_BACKED_TOKENS = {
    "DAI": (
        "MakerDAO. USDC is primary collateral via the Peg Stability Module "
        "(PSM), allowing 1:1 USDC-DAI swaps. At peak >50%% of DAI backing "
        "was USDC; as of 2024 still ~33%% of collateral."
    ),
    "FRAX": (
        "Frax Finance. USDC was the primary collateral in the fractional-"
        "algorithmic design and AMO system.  In 2023 governance moved to "
        "100%% collateralisation with USDC as the core reserve asset."
    ),
    "USDe": (
        "Ethena Labs. USDC is accepted as deposit collateral and held as a "
        "reserve buffer (~7%% of backing). Primary mechanism is delta-neutral "
        "hedging, but USDC exposure exists in the reserve structure."
    ),
    "OUSD": (
        "Origin Dollar. Backed by a basket of stablecoins deployed into DeFi "
        "yield strategies. Since Nov 2025 simplified to 100%% USDC backing. "
        "USDC was a primary collateral source throughout its history."
    ),
    "MIM": (
        "Abracadabra / Magic Internet Money. Key collateral types include "
        "yvUSDC (Yearn USDC vaults), giving MIM indirect but significant "
        "USDC exposure through yield-bearing USDC derivatives."
    ),
    "BOB": (
        "zkBob. Pegged almost entirely through USDC-paired concentrated "
        "liquidity on Uniswap V3.  All circulating BOB is backed 1:1 by "
        "on-chain stablecoin assets, primarily USDC."
    ),
    "alUSD": (
        "Alchemix. Minted against USDC (and DAI/USDT) deposits in Alchemix "
        "vaults; USDC yield automatically repays the loan. Redeemable for "
        "USDC via the Transmuter at 1:1."
    ),
    "cUSDC": (
        "Compound receipt token.  Each cUSDC represents a claim on USDC "
        "deposited into Compound plus accrued interest — a direct USDC "
        "derivative, not an independent stablecoin."
    ),
    "aUSDC": (
        "Aave receipt token.  Each aUSDC represents a claim on USDC "
        "deposited into Aave plus accrued interest — a direct USDC "
        "derivative, not an independent stablecoin."
    ),
    "USDC": (
        "USDC itself.  A USDC/USDT pool measures relative peg stability "
        "between the two stablecoins, not USDT independent liquidity."
    ),
}


def is_usdc_backed_usdt_pair(token0_sym, token1_sym, stablecoin):
    """Return True if this is a USDT pool whose counterpart is USDC-backed.

    Only applies to USDT pools; USDC pools are never excluded by this filter.
    """
    if stablecoin != "USDT":
        return False
    counterpart = token1_sym if token0_sym == "USDT" else token0_sym
    return counterpart in USDC_BACKED_TOKENS


# Path to the JSON file generated by findTopPools.py
_POOLS_JSON_PATH = os.path.join(
    os.path.dirname(__file__), "..", "..", "..", "data", "discovery", "selected_pools.json"
)


def _load_pools(json_path=_POOLS_JSON_PATH):
    """Load the pool registry from a JSON file.

    Raises FileNotFoundError with a helpful message if the file is missing
    (run findTopPools.py first to generate it).
    """
    resolved = os.path.normpath(json_path)
    if not os.path.isfile(resolved):
        raise FileNotFoundError(
            f"Pool registry not found at {resolved}. "
            "Run findTopPools.py to generate data/discovery/selected_pools.json."
        )
    with open(resolved) as f:
        return json.load(f)


# All tracked Uniswap V3 pools, loaded from JSON.
# Each entry: address -> {pair, fee_tier, stablecoin, active}
POOLS = _load_pools()


def get_active_pools():
    """Return dict of {address: trading_pair_label} for active pools only.

    The trading pair label is constructed as "TOKEN0TOKEN1<fee_tier>" to match
    the format used throughout the codebase (e.g., "DAIUSDC500", "USDCWETH3000").
    """
    return {
        address: info["pair"].replace("/", "") + str(info["fee_tier"])
        for address, info in POOLS.items()
        if info["active"]
    }


def get_pools_to_ignore():
    """Return list of pool addresses that are marked inactive."""
    return [addr for addr, info in POOLS.items() if not info["active"]]


def generate_pools_csv(output_path=None):
    """Generate the liquidity_pools_selected.csv used by the Messari hourly script.

    Columns: Pool ID, token0_symbol, token1_symbol, Fee Tier, Stablecoin
    Only includes active pools.
    """
    if output_path is None:
        output_path = os.path.join(
            os.path.dirname(__file__), "..", "..", "..", "data", "raw", "liquidity_pools_selected.csv"
        )

    rows = [
        {
            "Pool ID": address,
            "token0_symbol": info["pair"].split("/")[0],
            "token1_symbol": info["pair"].split("/")[1],
            "Fee Tier": info["fee_tier"],
            "Stablecoin": info["stablecoin"],
        }
        for address, info in POOLS.items()
        if info["active"]
    ]

    df = pd.DataFrame(rows)

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    df.to_csv(output_path, index=False)
    print(f"Wrote {len(df)} pools to {output_path}")
    return output_path
