"""
MCI_ticks.py — Compute Market Cost Impact (MCI) from tick-level data.

Simplified rewrite of MCI_ticks.py.  Pure functions, no classes, flat control
flow.  Does exactly the same thing:

  1. Find tick parquet files and pool TVL CSVs (daily or hourly) for a date range.
  2. For each timestamp, merge tick data with pool-level TVL.
  3. For every pool × level combination, compute buy/sell MCI via analytics_ticks.mci().
  4. Save per-pool detailed results + TVL-weighted averages per stablecoin.
  5. Concatenate all dates and save final mci_stats.parquet/.csv.

Modes:
    --hourly: use hourly TVL from pools_hourly (from getPoolData_hourly.py),
              matching each tick file to its exact hourly pool TVL CSV.
    default:  use daily TVL from pools_daily (from getPoolData_daily.py),
              matching each tick file to its corresponding daily pool TVL CSV.

Usage:
    python MCI_ticks.py --start_date 2023-03-01 --end_date 2023-03-01
    python MCI_ticks.py --hourly --start_date 2023-03-01 --end_date 2023-03-01
"""

import argparse
import glob
import os
import sys
import time
from collections import OrderedDict
from datetime import datetime
from decimal import Decimal
from multiprocessing import Pool, cpu_count

import numpy as np
import pandas as pd
from tqdm import tqdm

# ---------------------------------------------------------------------------
# Path setup so imports work when running from src/data/processing/
# ---------------------------------------------------------------------------
sys.path.append(os.path.join(os.path.dirname(__file__), "..", "..", ".."))

from src.modeling import analytics_ticks as an
# Old import: aggregate_to_hourly was needed to interpolate Messari hourly data
# from src.visualization.summaryTVL import aggregate_to_hourly
from src.data.collection.pools_config import get_pools_to_ignore, is_usdc_backed_usdt_pair, get_active_pools

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

# Trade sizes (in millions USD) at which to evaluate market depth
LEVELS = [1, 5, 10, 15, 20]

# Stablecoins whose MCI we aggregate
BASE_TOKENS = ["USDT", "USDC"]

# Pools excluded from TVL-weighted averages (but still in detailed output)
POOLS_SKIP_IN_WEIGHTED_AVG = ["USDCUSDT100"]

# Build the column list for the detailed per-pool output
_mci_cols = [f"MCI_{l}" for l in LEVELS]
_buy_cols = [f"Buy_MCI_{l}" for l in LEVELS]
_sell_cols = [f"Sell_MCI_{l}" for l in LEVELS]
_imb_cols = [f"MCI_imbalance_{l}" for l in LEVELS]
DETAIL_COLUMNS = (
    ["stablecoin", "token0_symbol", "token1_symbol", "fee_tier",
     "price_in_stablecoin", "totalValueLockedUSD"]
    + _mci_cols + _buy_cols + _sell_cols + _imb_cols
)

# Old column list (included vol_hourly from Messari hourly data)
# DETAIL_COLUMNS = (
#     ["stablecoin", "token0_symbol", "token1_symbol", "fee_tier",
#      "price_in_stablecoin", "vol_hourly", "totalValueLockedUSD"]
#     + _mci_cols + _buy_cols + _sell_cols + _imb_cols
# )

# Columns from the daily pool TVL CSVs (generated by getPoolData_daily.py)
POOL_CSV_COLS = [
    "pool_address", "totalValueLockedUSD", "trading_pair", "stablecoin",
]

# Old columns from Messari hourly pool CSVs
# POOL_CSV_COLS = [
#     "date", "totalValueLockedUSD", "hourlyVolumeUSD",
#     "pool_address", "trading_pair", "stablecoin",
# ]


# ===================================================================
# File discovery
# ===================================================================

def find_files(directory, start_date, end_date, ext=".csv",
               date_fmt="%Y-%m-%d %H-%M-%S", year="2023"):
    """Glob for data files and filter to [start_date, end_date].

    Returns an OrderedDict  {datetime -> filepath}  sorted by date.
    """
    pattern = os.path.join(directory, f"**/*{ext}")
    paths = glob.glob(pattern, recursive=True)

    start_dt = datetime.strptime(start_date, "%Y-%m-%d")
    end_dt = datetime.strptime(end_date, "%Y-%m-%d")

    result = {}
    for p in paths:
        if year not in p:
            continue
        basename = os.path.basename(p).split(".")[0]
        try:
            dt = datetime.strptime(basename, date_fmt)
        except ValueError:
            continue
        if start_dt <= dt <= end_dt:
            result[dt] = p

    return OrderedDict(sorted(result.items()))


# ===================================================================
# Data preparation
# ===================================================================

def prepare_data(tick_df, pools_df, pairs_filter=None):
    """Merge tick-level data with daily pool TVL for one date.

    Args:
        tick_df:       Tick-level parquet data for a single timestamp.
        pools_df:      Daily pool TVL from getPoolData_daily.py (one row per pool).
        pairs_filter:  Optional list of trading_pair strings to keep.

    Steps:
      - Build a 'trading_pair' key on the tick side and inner-join with pool TVL.
      - Normalise token symbol names (some come as full names).
      - Drop ignored pools (from pools_config).
      - Filter USDT pools with USDC-backed counterparts.
      - Optionally keep only pairs in *pairs_filter*.
    """
    # Build the join key on the tick side:  "USDCWETH500"
    tick_df = tick_df.copy()
    tick_df["pool_address"] = tick_df["pool_address"].str.lower()
    tick_df["trading_pair"] = (
        tick_df["token0_symbol"] + tick_df["token1_symbol"]
        + tick_df["fee_tier"].astype(str)
    )

    # Keep only TVL + stablecoin from pool data, keyed by trading_pair
    pool_tvl = pools_df[["trading_pair", "totalValueLockedUSD", "stablecoin"]].copy()
    pool_tvl = pool_tvl.drop_duplicates(subset=["trading_pair"], keep="first")

    # Inner join — only pools present in both datasets survive
    merged = tick_df.merge(pool_tvl, on="trading_pair", how="inner")

    # Some on-chain token symbols are full names; normalise to ticker
    name_to_ticker = {"USD Coin": "USDC", "Tether USD": "USDT"}
    merged["token0_symbol"] = merged["token0_symbol"].replace(name_to_ticker)
    merged["token1_symbol"] = merged["token1_symbol"].replace(name_to_ticker)

    # Filter specific pairs if requested
    if pairs_filter:
        merged = merged[merged["trading_pair"].isin(pairs_filter)]

    # Remove pools marked as inactive in the central config
    ignored = get_pools_to_ignore()
    merged = merged[~merged["pool_address"].isin(ignored)]

    # Get pools to use
    use_pools = get_active_pools()
    merged = merged[merged["pool_address"].isin(use_pools)]

    # Remove USDT pools whose counterpart token is USDC-backed
    usdc_backed_mask = merged.apply(
        lambda r: is_usdc_backed_usdt_pair(
            r["token0_symbol"], r["token1_symbol"], r["stablecoin"]
        ),
        axis=1,
    )
    merged = merged[~usdc_backed_mask]

    return merged


# Old prepare_data that merged with Messari hourly data
# def prepare_data(tick_df, pools_df, date_dt, pairs_filter=None):
#     """Merge tick-level data with Messari hourly pool stats for one date."""
#     # Aggregate Messari pool data to hourly (forward/back-fills gaps)
#     pools_df = aggregate_to_hourly(pools_df)
#     pools_df = pools_df.drop(columns=["pool_address"])
#     target_hour = pd.Timestamp(date_dt).floor("h")
#     pools_df = pools_df[pools_df["date"] == target_hour]
#
#     tick_df = tick_df.copy()
#     tick_df["pool_address"] = tick_df["pool_address"].str.lower()
#     tick_df["trading_pair"] = (
#         tick_df["token0_symbol"] + tick_df["token1_symbol"]
#         + tick_df["fee_tier"].astype(str)
#     )
#     merged = tick_df.merge(pools_df, on="trading_pair", how="inner")
#
#     name_to_ticker = {"USD Coin": "USDC", "Tether USD": "USDT"}
#     merged["token0_symbol"] = merged["token0_symbol"].replace(name_to_ticker)
#     merged["token1_symbol"] = merged["token1_symbol"].replace(name_to_ticker)
#
#     if pairs_filter:
#         merged = merged[merged["trading_pair"].isin(pairs_filter)]
#
#     ignored = get_pools_to_ignore()
#     merged = merged[~merged["pool_address"].isin(ignored)]
#
#     usdc_backed_mask = merged.apply(
#         lambda r: is_usdc_backed_usdt_pair(
#             r["token0_symbol"], r["token1_symbol"], r["stablecoin"]
#         ),
#         axis=1,
#     )
#     merged = merged[~usdc_backed_mask]
#     return merged


# ===================================================================
# MCI calculation  (per-pool, per-level)
# ===================================================================

def compute_mci_for_level(ticks_df, level, mid_price, tick_spacing,
                          decimals0, decimals1, sqrt_price_x96,
                          pair, date_str, flip_flag):
    """Compute buy MCI, sell MCI, average, and imbalance for one level.

    Returns (mci_avg, mci_imbalance, buy_mci, sell_mci).
    All zeros when depth is insufficient.
    """
    ticks_df = ticks_df.reset_index(drop=True)

    buy_mci = an.mci(
        is_bid=False, level=level, mid_price=mid_price,
        ticks=ticks_df, tick_spacing=tick_spacing,
        decimals0=decimals0, decimals1=decimals1,
        sqrt_price_x96=sqrt_price_x96,
        pair=pair, date_val=date_str, flip_flag=flip_flag,
    )

    sell_mci = an.mci(
        is_bid=True, level=level, mid_price=mid_price,
        ticks=ticks_df, tick_spacing=tick_spacing,
        decimals0=decimals0, decimals1=decimals1,
        sqrt_price_x96=sqrt_price_x96,
        pair=pair, date_val=date_str, flip_flag=flip_flag,
    )

    # Both zero means depth was insufficient at this level
    if buy_mci == 0 and sell_mci == 0:
        return 0.0, 0.0, 0.0, 0.0

    avg = (buy_mci + sell_mci) / 2
    imbalance = (buy_mci - sell_mci) / (buy_mci + sell_mci)
    return avg, imbalance, buy_mci, sell_mci


def compute_mci_all_pools(merged_df, date_str, levels=LEVELS,
                          base_tokens=BASE_TOKENS):
    """Compute MCI for every pool in *merged_df* across all levels.

    Returns a DataFrame with one row per pool (columns = DETAIL_COLUMNS).
    """
    rows = []

    for pair in merged_df["trading_pair"].unique():
        sub = merged_df[merged_df["trading_pair"] == pair]
        first = sub.iloc[0]

        mid_price = Decimal(first["price_in_stablecoin"])
        token0 = first["token0_symbol"]
        token1 = first["token1_symbol"]
        decimals0 = int(first["token0_decimals"])
        decimals1 = int(first["token1_decimals"])
        sqrt_px96 = int(first["sqrt_price_x96"])
        tick_sp = first["tick_spacing"]
        fee = int(first["fee_tier"])
        tvl = float(first["totalValueLockedUSD"])

        # Old: hourly volume from Messari (no longer needed)
        # vol = float(first["hourlyVolumeUSD"])

        # flip_flag: True when token1 is NOT the stablecoin
        flip = token1 not in base_tokens
        stablecoin = token0 if flip else token1

        print(f"  {pair}  (TVL ${tvl:,.0f})")

        mcis, imbs, buys, sells = [], [], [], []
        for level in levels:
            avg, imb, buy, sell = compute_mci_for_level(
                sub, level, mid_price, tick_sp,
                decimals0, decimals1, sqrt_px96,
                pair, date_str, flip,
            )
            mcis.append(avg)
            imbs.append(imb)
            buys.append(buy)
            sells.append(sell)

        rows.append(
            [stablecoin, token0, token1, fee, mid_price, tvl]
            + mcis + buys + sells + imbs
        )

        # Old row format (included vol):
        # rows.append(
        #     [stablecoin, token0, token1, fee, mid_price, vol, tvl]
        #     + mcis + buys + sells + imbs
        # )

    return pd.DataFrame(rows, columns=DETAIL_COLUMNS)


# ===================================================================
# Weighted averages across pools for each stablecoin
# ===================================================================

def compute_weighted_averages(detail_df, sizes=SIZES,
                              base_tokens=BASE_TOKENS):
    """TVL-weighted average of MCI columns, grouped by stablecoin.

    Pools in POOLS_SKIP_IN_WEIGHTED_AVG are excluded from the average
    (but kept in the detailed output).
    """
    metric_cols = (
        [f"MCI_{s}" for s in sizes]
        + [f"Buy_MCI_{s}" for s in sizes]
        + [f"Sell_MCI_{s}" for s in sizes]
        + [f"MCI_imbalance_{s}" for s in sizes]
    )

    df = detail_df.copy().fillna(0)

    # Build pool id label for filtering
    df["pool_id"] = (
        df["token0_symbol"] + df["token1_symbol"] + df["fee_tier"].astype(str)
    )
    df = df[~df["pool_id"].isin(POOLS_SKIP_IN_WEIGHTED_AVG)]

    # Weighted average per stablecoin, weighted by TVL
    weighted = pd.DataFrame(columns=metric_cols, index=base_tokens)
    for col in metric_cols:
        weighted[col] = df.groupby("stablecoin").apply(
            lambda g: np.average(g[col], weights=g["totalValueLockedUSD"])
        )

    return weighted


# ===================================================================
# Single-date processing  (entry point for multiprocessing workers)
# ===================================================================

def process_one_date(args_tuple):
    """Process a single date: load data, compute MCI, save results.

    Designed to be called via multiprocessing.Pool.imap().  Accepts a single
    tuple so it's compatible with pool.imap / pool.map.

    Returns the weighted-averages DataFrame for this date.
    """
    (date_dt, start_date, end_date,
     tick_file, pool_file, output_dir) = args_tuple

    # date_str is used for filenames and display (e.g. "2023-03-01 00-00-00")
    date_str = date_dt.strftime("%Y-%m-%d %H-%M-%S")

    # Output paths
    mci_dir = os.path.join(output_dir, "mci_ticks")
    detail_dir = os.path.join(output_dir, "mci_detailed_ticks")
    os.makedirs(mci_dir, exist_ok=True)
    os.makedirs(detail_dir, exist_ok=True)

    basename = os.path.basename(tick_file).split(".")[0]
    mci_path = os.path.join(mci_dir, f"{basename}.parquet")
    detail_path = os.path.join(detail_dir, f"{basename}.parquet")

    # Skip if already computed
    if os.path.exists(mci_path):
        print(f"Already done: {basename}")
        return pd.read_parquet(mci_path, engine="fastparquet")

    # ---- Load data ----
    print(f"Loading {tick_file} ...")
    tick_df = pd.read_parquet(tick_file, engine="fastparquet")

    # Load daily pool TVL (from getPoolData_daily.py)
    pool_df = pd.read_csv(pool_file, engine="c", usecols=POOL_CSV_COLS)

    # Old: load Messari hourly CSV with different columns
    # pool_df = pd.read_csv(pool_file, engine="c", usecols=[
    #     "date", "totalValueLockedUSD", "hourlyVolumeUSD",
    #     "pool_address", "trading_pair", "stablecoin",
    # ])

    # ---- Merge tick + pool data ----
    merged = prepare_data(tick_df, pool_df)

    # Old: passed date_dt for hourly filtering of Messari data
    # merged = prepare_data(tick_df, pool_df, date_dt)

    if merged.empty:
        print(f"WARNING: No data after merge for {date_str}, skipping")
        return pd.DataFrame()

    # ---- Compute MCI for every pool ----
    print(f"Computing MCI for {date_str} ...")
    detail_df = compute_mci_all_pools(merged, date_str)

    # ---- Save detailed per-pool results ----
    detail_df.to_parquet(detail_path, index=False, engine="fastparquet")
    detail_df.to_csv(detail_path.replace(".parquet", ".csv"), index=False)

    # ---- Compute TVL-weighted averages per stablecoin ----
    weighted = compute_weighted_averages(detail_df)
    weighted["date"] = date_str
    weighted = weighted.reset_index().rename(columns={"index": "stablecoin"})

    # ---- Save weighted averages ----
    weighted.to_parquet(mci_path, index=False, engine="fastparquet")
    weighted.to_csv(mci_path.replace(".parquet", ".csv"), index=False)

    return weighted


# ===================================================================
# CLI  &  main orchestration
# ===================================================================

def parse_args():
    p = argparse.ArgumentParser(
        description="Compute MCI from tick data (simplified v2)")

    p.add_argument("--filtered_files", default="./../../../data/filtered",
                   help="Base directory for filtered / output data")

    p.add_argument("--ticks_files", default="./../../../data/pools/rpc",
                   help="Directory containing tick parquet files")

    # Pool TVL source (overridden automatically when --hourly is used)
    p.add_argument("--pools_files", default=None,
                   help="Directory containing pool TVL CSVs "
                        "(default: pools_daily or pools_hourly based on mode)")

    p.add_argument("--hourly", action="store_true",
                   help="Use hourly pool TVL from pools_hourly "
                        "(default: daily from pools_daily)")

    p.add_argument("--start_date", default="2023-02-28")
    p.add_argument("--end_date", default="2023-04-01")
    p.add_argument("--num_cpus", type=int, default=2,
                   help="CPUs: -1=all, 1=1/3, 2=2/3, other=1/2")

    return p.parse_args()


def pick_cpu_count(requested):
    """Translate the --num_cpus flag into an actual process count."""
    total = cpu_count()
    mapping = {-1: total, 1: max(1, total // 3), 2: max(1, total * 2 // 3)}
    n = mapping.get(requested, max(1, total // 2))
    print(f"Using {n} / {total} CPUs")
    return n


def main():
    args = parse_args()
    hourly = args.hourly

    # Default pool TVL directory based on mode
    if args.pools_files is None:
        if hourly:
            args.pools_files = os.path.join(args.filtered_files, "pools_hourly")
        else:
            args.pools_files = os.path.join(args.filtered_files, "pools_daily")

    # ---- Discover files for the date range ----
    tick_files = find_files(
        args.ticks_files, args.start_date, args.end_date,
        ext=".parquet", date_fmt="%Y-%m-%d %H-%M-%S",
    )

    if hourly:
        # Hourly mode: match each tick file to its exact hourly pool TVL CSV
        pool_files = find_files(
            args.pools_files, args.start_date, args.end_date,
            ext=".csv", date_fmt="%Y-%m-%d %H-%M-%S",
        )
        pool_files = {k.strftime("%Y-%m-%d %H-%M-%S"): v
                      for k, v in pool_files.items()}
    else:
        # Daily mode: match each tick file to its corresponding daily pool CSV
        pool_files = find_files(
            args.pools_files, args.start_date, args.end_date,
            ext=".csv", date_fmt="%Y-%m-%d",
        )
        pool_files = {k.strftime("%Y-%m-%d"): v for k, v in pool_files.items()}

    if not tick_files:
        raise FileNotFoundError(
            f"No tick parquet files found in {args.ticks_files} "
            f"for {args.start_date} .. {args.end_date}"
        )

    # ---- Build work items (one per timestamp) ----
    # Match tick files to pool TVL files by datetime (hourly) or date (daily)
    pool_key_fmt = "%Y-%m-%d %H-%M-%S" if hourly else "%Y-%m-%d"
    work = []
    for dt, tfile in tick_files.items():
        key = dt.strftime(pool_key_fmt)
        if key not in pool_files:
            print(f"WARNING: No pool TVL file for {key}, skipping")
            continue
        work.append(
            (dt, args.start_date, args.end_date, tfile,
             pool_files[key], args.filtered_files)
        )

    # ---- Run with multiprocessing ----
    n_cpus = pick_cpu_count(args.num_cpus)

    with Pool(processes=n_cpus) as pool:
        results = list(tqdm(
            pool.imap(process_one_date, work),
            total=len(work),
            desc="MCI processing",
        ))

    # ---- Concatenate all dates and save final output ----
    final_df = pd.concat(results)
    out_path = os.path.join(args.filtered_files, "mci_stats.parquet")
    final_df.to_parquet(out_path, index=False, engine="fastparquet")
    final_df.to_csv(out_path.replace(".parquet", ".csv"), index=False)
    print(f"Saved final MCI stats to {out_path}")


if __name__ == "__main__":
    t0 = time.time()
    main()
    print(f"Done in {time.time() - t0:.1f}s")
